runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "abc-jobs-miso-uniandes-g14"

handlers:
- url: /
  static_files: dist/abc-jobs-ui/index.html
  upload: dist/abc-jobs-ui/index.html

- url: /
  static_dir: dist/abc-jobs-ui
