runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "abc-jobs-miso-uniandes-g14"

handlers:
- url: /(.*\.(gif|png|jpg|jpeg|css|js)(|\.map))$
  static_files: dist/abc-jobs-ui/\1
  upload: dist/abc-jobs-ui/(.*\.(gif|png|jpg|jpeg|css|js)(|\.map))$

- url: /.*
  static_files: dist/abc-jobs-ui/index.html
  upload: dist/abc-jobs-ui/index.html
